- name: dash-bran
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: monday

        - type: twitch-channels
          channels:
            - picco
            - dorozea
            - xqc
            - theprimeagen

    - size: full
      widgets:
        - type: videos
          channels:
            - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
            - UCNAf1k0yIjyGu3k9BwAg3lg # Sky Sports Premier League
            - UCsBjURrPoezykLs9EqgamOA # Fireship
            - UCfpCQ89W9wjkHc8J_6eTbBg # Outdoor Boys
            - UC9UKCabwn8KjiDt8zrFjwFw # RedDevilsLatest

        - type: group
          widgets:
            - type: reddit
              subreddit: LivestreamFail
              show-thumbnails: true
            - type: reddit
              subreddit: worldnews
              show-thumbnails: true
            - type: reddit
              subreddit: ableton
              show-thumbnails: true
            - type: reddit
              subreddit: playrust
              show-thumbnails: true
            - type: reddit
              subreddit: linustechtips
              show-thumbnails: true

    - size: small
      widgets:
        - type: weather
          location: York, United Kingdom
          units: metric # alternatively "imperial"
          hour-format: 12h # alternatively "24h"
          # Optionally hide the location from being displayed in the widget
          # hide-location: true

        - type: markets
          markets:
            - symbol: SPY
              name: S&P 500
            - symbol: BTC-USD
              name: Bitcoin

        - type: repository
          repository: brandon-carlisle/dash
          pull-requests-limit: -1
          issues-limit: -1
          commits-limit: 3

        - type: repository
          repository: brandon-carlisle/stadiumguessr
          pull-requests-limit: -1
          issues-limit: -1
          commits-limit: 3
